# Name of your application. Used to uniquely configure containers.
service: velotrain

# Name of the container image.
image: clementf/velotrain

aliases:
  console: app exec --reuse -i "bin/rails console"

# Deploy to these servers.
servers:
  web:
    hosts:
      - 49.13.228.65

proxy:
  ssl: true
  app_port: 3000
  hosts:
    - velotrain.fr

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  server: rg.fr-par.scw.cloud
  username: clementf

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch:
    - amd64

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    PORT: 3000
  secret:
    - POSTGRES_PASSWORD
    - DATABASE_URL
    - SECRET_KEY_BASE
    - RAILS_MASTER_KEY

accessories:
  pg:
    image: postgis/postgis:14-3.4
    host: 49.13.228.65
    port: "5433:5432"
    env:
      clear:
        POSTGRES_USER: 'velotrain'
        POSTGRES_DB: 'velotrain_production'
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
